### ISSUE TITLE
Is -> Are

### ISSUE THREAD

**Issue by AntonyMoes** [OneLastTimeTeam/city_emotions_android#2]
https://github.com/OneLastTimeTeam/city_emotions_android/blob/408e5c1f698d133e756790ad65fd7559d2837f7c/app/src/main/java/com/example/cityemotions/fragments/MapScreenFragment.kt#L67

**Comment by Xenobyte42** [comment]
Fixed in be6035874187cee0fad9bb66ead28046ca70d8e8
