### ISSUE TITLE
По заповедям чистого кода

### ISSUE THREAD

**Issue by neikila** [OneLastTimeTeam/city_emotions_android#4]
https://github.com/OneLastTimeTeam/city_emotions_android/blob/5df7bf97508adf06dcd248918694c7318c77a62c/app/src/main/java/com/example/cityemotions/fragments/MapScreenFragment.kt#L280

В общем случае Я бы настоятельно рекомендовал не проглатывать совсем исключения.
Стоит вывести хотя бы в лог Log.e(....) мне это уже далеко не раз помогло.

**Comment by Xenobyte42** [comment]
Fixed in ebd492cc52e721a33e55ccf2a8304a9aaa542857
