### ISSUE TITLE
Как насчет локали?

### ISSUE THREAD

**Issue by neikila** [OneLastTimeTeam/city_emotions_android#7]
https://github.com/OneLastTimeTeam/city_emotions_android/blob/5df7bf97508adf06dcd248918694c7318c77a62c/app/src/main/java/com/example/cityemotions/datamodels/MarkerModel.kt#L13

Лучше заменить happy на R.string.happy_emoji_title

**Comment by Xenobyte42** [comment]
Fixed in ebd492cc52e721a33e55ccf2a8304a9aaa542857
